- name: create a user using a variable
  hosts: my_node_1_cagatay
  become: true
  vars:
    user: cagatay
  tasks:
    - name: create a user {{ user }}
      user:
        name: "{{ user }}"

    - debug:
        msg: "private ip is {{ private_id }}"

    - debug:
        msg: "instance id is {{ ec2_id }}"

    - debug:
        msg: "my key file is {{ key }}"

    - debug: 
        msg: "host is  {{ ansible_host }}"
