- name: create a user
  hosts: all
  become: yes
  vars_files:
  - secret1.yaml
  tasks:
  - name: create a user
    user:
      name: "{{ username }}"
      password: "{{ password | password_hash ('sha512') }}" 
